// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRqJacJXKAyTYYbV020rx6QT5G7hixDN8',
    appId: '1:34643633359:web:af63f994eca0c306ab83ba',
    messagingSenderId: '34643633359',
    projectId: 'scheduletdl',
    authDomain: 'scheduletdl.firebaseapp.com',
    storageBucket: 'scheduletdl.appspot.com',
    measurementId: 'G-NLQC7GX64F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvC3HcwHIhFVOaMQqHb6YX7N3AM7l-vw0',
    appId: '1:34643633359:android:fadc36d6890c59d4ab83ba',
    messagingSenderId: '34643633359',
    projectId: 'scheduletdl',
    storageBucket: 'scheduletdl.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5ZPHi4NcFMtT_I7_zxu1cgANPrvuJrtU',
    appId: '1:34643633359:ios:6b128620fc6f0098ab83ba',
    messagingSenderId: '34643633359',
    projectId: 'scheduletdl',
    storageBucket: 'scheduletdl.appspot.com',
    iosClientId: '34643633359-q4l8abgqbim2o8he131g50gdn444a7i3.apps.googleusercontent.com',
    iosBundleId: 'com.example.scheduletdl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5ZPHi4NcFMtT_I7_zxu1cgANPrvuJrtU',
    appId: '1:34643633359:ios:6b128620fc6f0098ab83ba',
    messagingSenderId: '34643633359',
    projectId: 'scheduletdl',
    storageBucket: 'scheduletdl.appspot.com',
    iosClientId: '34643633359-q4l8abgqbim2o8he131g50gdn444a7i3.apps.googleusercontent.com',
    iosBundleId: 'com.example.scheduletdl',
  );
}
